# Generated by Django 4.0.4 on 2022-05-05 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iin', models.TextField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
