# Generated by Django 4.0.4 on 2022-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_keystore_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keystore',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
