# Generated by Django 4.0.4 on 2022-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_keystore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
