INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Introduction to Programming (С++)', 5, 'VPС1213', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Introduction to Programming (Java)', 5, 'VPJ1213', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Professional English', 5, 'PAYa1211', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Educational practice_hours', 2, 'UP1212', 'REPORT', 0, 0, 40, 20);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Database Management Systems', 5, 'DBMS2204', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Computer Organisation and Architecture', 5, 'COA2207', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('WEB Technologies', 5, 'VW1209', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Algorithms and Data Structures', 5, 'ASD1206', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Design Patterns (Java)', 5, 'SDPJ2216', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Design Patterns (C#)', 5, 'SPDC2216', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Coding Lab', 5, 'CL1215', 'PROJECT', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Innovation Lab', 6, 'IL1215', 'PROJECT', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Object-Oriented Programming (Java)', 5, 'OOPJ1214', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Object-Oriented Programming (Python)', 5, 'OOPP1214', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Introduction to Programming (Python)', 5, 'VPP1213', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Object-Oriented Programming (C++)', 5, 'OOPС1214', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Political Science', 2, 'Pol2109', 'EXAM', 10, 10, 30, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Sociology', 2, 'Soc3110', 'EXAM', 10, 10, 30, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Information and Communication Technologies', 5, 'IKT1107', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Psychology', 2, 'Psy2108', 'EXAM', 10, 10, 30, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Kazakh Language', 5, 'KYa2105', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Russian Language', 5, 'RYa2106', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Foreign Language (English)', 5, 'IYa1103', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Linear Algebra', 5, 'AG1201', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Foreign Language (English)', 5, 'IYa1104', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Probability and Statistics', 5, 'TViMS2210', 'EXAM', 20, 30, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Calculus 2', 5, 'MA21203', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Discrete Mathematics', 5, 'DM1205', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Technological Entrepreneurship', 5, 'TP3113', 'EXAM', 20, 30, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Calculus 1', 5, 'MA11202', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Cultural Studies', 2, 'Cult1111', 'EXAM', 10, 10, 30, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Physical Culture', 2, 'Fiz1112', 'зачет', 0, 80, 120, 40);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Modern History of Kazakhstan', 5, 'SIK1101', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Philosophy ', 5, 'FIL3102', 'EXAM', 30, 20, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Machine Learning Algorithms', 5, 'MLA3303', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Cloud Computing Applications', 5, 'CCA3304', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Process Management', 5, 'SPM3301', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Factory', 5, 'SFP2302', 'PROJECT', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Mastering Design Thinking', 5, 'MDS3224', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Performance Analysis_hours', 5, 'SPE2223', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Undergraduate practice_hours', 4, 'PP3312', 'REPORT', 0, 0, 100, 20);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Research Methods and Tools', 4, 'RMT3309', 'EXAM', 0, 40, 70, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Рroject Management', 5, 'UP3307', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Information Security Fundamentals', 5, 'ISA3308', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Quality Assurance and Testing', 5, 'SQA3305', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Distributed Algorithms and Parallel Computing', 5, 'DAPC3306', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 2 (C#)', 5, 'AdCP22219', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 2 (Python)', 5, 'AdPP12219', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 1 (Python)', 5, 'AdPP12218', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 2 (Java)', 5, 'AdJP22219', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 1 (Java)', 5, 'AdJP12218', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Advanced Programming 1 (C#)', 5, 'AdCP12218', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Operating Systems and Computer Networks', 5, 'OSCN2217', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Operating Systems Security', 5, 'OSS2217', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Software Architecture', 5, 'SA2222', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Mobile Development 2 (Android) ', 5, 'AnD22221', 'EXAM', 0, 50, 90, 10);
INSERT INTO syllabus_course (name, credits, code, control_type, lecture_hours, practice_hours, sis_hours, tsis_hours) VALUES ('Mobile Development 1 (Android) ', 5, 'AnD12220', 'EXAM', 0, 50, 90, 10);
