# Generated by Django 4.0.4 on 2022-05-08 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В работе'), ('ON_APPROVING', 'На согласовании'), ('ON_REGISTRATION', 'На регистрации'), ('ACTIVE', 'Действителен'), ('ON_REWORK', 'На доработке')], max_length=40)),
                ('language', models.CharField(choices=[('KZ', 'Казахский'), ('RU', 'Русский'), ('EN', 'Английский')], max_length=40)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('tasks', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('metodic', models.TextField(blank=True, null=True)),
                ('notation', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('readings', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='syllabus.course')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='syllabus.evaluation')),
                ('post_codes', models.ManyToManyField(related_name='syllabuses_post', to='syllabus.course')),
                ('pre_codes', models.ManyToManyField(related_name='syllabuses_pre', to='syllabus.course')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='syllabus.rubric')),
                ('teacher', models.ManyToManyField(related_name='syllabuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='syllabus.faculty'),
        ),
    ]
