# Generated by Django 4.0.4 on 2022-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_remove_course_year_course_control_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
