# Generated by Django 4.0.4 on 2022-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_evaluation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('materials', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='syllabus',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='syllabus.topic'),
        ),
    ]
