# Generated by Django 4.0.4 on 2022-05-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_topic_syllabus_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='week',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
