# Generated by Django 4.0.4 on 2022-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='post_courses',
            field=models.ManyToManyField(default=[], related_name='syllabuses_post', to='syllabus.course'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pre_courses',
            field=models.ManyToManyField(default=[], related_name='syllabuses_pre', to='syllabus.course'),
        ),
    ]
