# Generated by Django 4.0.4 on 2022-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_alter_syllabus_post_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='sign_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='approver',
            name='sign_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approver',
            name='signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
